version: 2
updates:
- package-ecosystem: "maven"
  directory: "/benchmark"
  schedule:
    interval: "daily"
- package-ecosystem: "pip"
  directory: "/orchestration/v1"
  schedule:
    interval: "daily"
- package-ecosystem: "maven"
  directory: "/orchestration/v2"
  schedule:
    interval: "daily"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
