name: Test & Publish Image

on:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build & Test with Maven
        run: |
          pushd benchmark
            mvn --batch-mode --update-snapshots verify
          popd
          pushd orchestration/v2
            mvn --batch-mode --update-snapshots verify
          popd

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Tags
        id: prep
        run: |
          set -euxo pipefail
          DOCKER_IMAGE=pivotalrabbitmq/rabbittesttool
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            TAGS="${DOCKER_IMAGE}:${VERSION},${DOCKER_IMAGE}:${GITHUB_SHA},${DOCKER_IMAGE}:latest"
          else
            TAGS="${DOCKER_IMAGE}:${GITHUB_SHA},${DOCKER_IMAGE}:dev"
          fi
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./benchmark
          file: ./benchmark/Dockerfile
          push: true
          tags: ${{ steps.prep.outputs.tags }}
